version: '3'
services:
  geth:
    build: geth
    image: geth
    container_name: geth
    command: --networkid 1865 --nodiscover --maxpeers=0 --datadir=/root/.ethereum --mine --minerthreads=1 --rpc --rpcport=8545 --rpccorsdomain='*' --rpcapi=admin,db,debug,eth,miner,net,personal,shh,txpool,web3 --ws --wsaddr=0.0.0.0 --wsport=8546 --wsorigins='*' --wsapi=admin,db,debug,eth,miner,net,personal,shh,txpool,web3
    ports:
      - 8545-8546:8545-8546
      - 30303:30303
      - 30303:30303/udp
